# Copyright (c) 2016 Genome Research Ltd.
#
# Author: Christopher Harrison <ch12@sanger.ac.uk>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
---
# file: roles/irods/tasks/jansson.yml
- name: Download Jansson
  get_url:
    url: "{{ jansson_url }}"
    dest: "{{ ansible_env.HOME }}/jansson-{{ jansson_version }}.tar.gz"
  register: jansson_downloaded

- name: Extract Jansson
  unarchive:
    src: "{{ ansible_env.HOME }}/jansson-{{ jansson_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/jansson-{{ jansson_version }}/LICENSE"
    copy: no
  when: jansson_downloaded|succeeded
  register: jansson_extracted

- name: Build Jansson
  command: "{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/jansson-{{ jansson_version }}"
    creates: /usr/local/lib/libjansson.so
  with_items:
    - ./configure
    - make
    - make install
  become: true
  when: jansson_extracted|succeeded
