# Copyright (c) 2017 Genome Research Ltd.
#
# Authors: 
#   Colin Nolan <colin.nolan@sanger.ac.uk>
#   Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# file: roles/consul-server/tasks/main.yml
---

# TODO: Should common ensure this is setup?
- name: setup to install packages from PyPi
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items:
    - python
    - python-pip

- name: install pre-requisite Python modules for managing Consul ACL tokens
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - python-consul
    - pyhcl
