# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/consul-server/meta/main.yml

dependencies:
  - common
  - role: attached-openstack-volume
    attached_openstack_volume_vg: consul-vg
    attached_openstack_volume_vols:
      - name: consul-data
        size: "{{ (hostvars[volume]['openstack_volume_size_gb'] * 1024) - 4 }}M"
        fstype: xfs
        mountpoint: "{{ consul_data_mountpoint }}"
  - role: ansible-consul
    become: yes
  - role: s3-backup
    s3_backup_source: "{{ consul_data_dir }}"
    s3_backup_destination: "s3://{{ consul_backup_bucket }}"
    s3_backup_s3_host: "{{ s3_host }}"
    s3_backup_s3_access_key: "{{ s3_access_key }}"
    s3_backup_s3_secret_key: "{{ s3_secret_key }}"
