# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/tasks/root.yml

- name: ensure we have essential Debian/Ubuntu packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  tags:
    - package
    - common
  with_items:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - cloud-init
    - gnupg2
    - sudo
  when: ansible_os_family == 'Debian'

#- name: ensure unwanted Ubuntu 16.04 packages are absent
#  become: yes
#  apt: name={{ item }} state=absent update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
#  tags:
#    - package
#    - common
#  with_items:
#    - unattended-upgrades
#  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_version == '16.04') 

- name: disable unattended upgrades (systemd)
  tags: common
  become: yes
  lineinfile: 
    dest: '/etc/apt/apt.conf.d/10periodic'
    line: 'APT::Periodic::Enable "0";'
    regexp: 'APT::Periodic::Enable'
  when: (ansible_distribution == 'Ubuntu') and (ansible_service_mgr == 'systemd')

- name: setup cloud-init to manage /etc/hosts
  tags: common
  become: yes
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: present
    regexp: "^manage_etc_hosts:"
    line: "manage_etc_hosts: true"

#- name: upgrade existing APT packages 
#  become: yes
#  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }} upgrade=yes
#  tags:
#    - package
#    - common
#  when: ansible_os_family == 'Debian'

- name: add cron job to clean up leaking systemd login unit files (https://github.com/systemd/systemd/issues/1961)
  become: yes
  cron:
    name: remove systemd scope files
    weekday: *
    minute: 0
    hour: */4
    user: root
    job: "/bin/rm -f /run/systemd/system/*.scope"
    cron_file: systemd-fix-1961-leaking-login-units

- name: common root configuration not to be baked into images
  include: root-post-image-building.yml
  when: "not 'image-building' in group_names"

