# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/tasks/root.yml

- name: ensure we have essential Debian/Ubuntu packages
  become: yes
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  tags:
    - package
    - common
  with_items:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - cloud-init
    - gnupg2
    - sudo
  when: ansible_os_family == 'Debian'

#- name: ensure unwanted Ubuntu 16.04 packages are absent
#  become: yes
#  apt: name={{ item }} state=absent update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
#  tags:
#    - package
#    - common
#  with_items:
#    - unattended-upgrades
#  when: (ansible_distribution == 'Ubuntu') and (ansible_distribution_version == '16.04') 

- name: disable unattended upgrades (systemd)
  tags: common
  become: yes
  lineinfile: 
    dest: '/etc/apt/apt.conf.d/10periodic'
    line: 'APT::Periodic::Enable "0";'
    regexp: 'APT::Periodic::Enable'
  when: (ansible_distribution == 'Ubuntu') and (ansible_service_mgr == 'systemd')

- name: setup cloud-init to manage /etc/hosts
  tags: common
  become: yes
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: present
    regexp: "^manage_etc_hosts:"
    line: "manage_etc_hosts: true"

#- name: upgrade existing APT packages 
#  become: yes
#  apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }} upgrade=yes
#  tags:
#    - package
#    - common
#  when: ansible_os_family == 'Debian'

- name: install GRL CA cert
  become: yes
  copy:
    src: grl-cacert.pem
    dest: /usr/local/share/ca-certificates/grl-cacert.crt
  tags:
    - common
  notify: update ca certificates

- name: create hgi group
  tags: common
  become: yes
  group:
    name: hgi
    gid: 1313

- name: create mercury user account
  tags: common
  become: yes
  user: 
    name: mercury
    uid: 13912
    group: hgi
    shell: /bin/bash

- name: give mercury NOPASSWD sudo access
  tags: common
  become: yes
  template:
    src: mercury_sudoers.j2
    dest: /etc/sudoers.d/mercury-nopasswd
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: 0440

- name: set authorized keys for mercury
  tags: common
  become: yes
  authorized_key:
    user: mercury
    manage_dir: yes
    state: present
    key: "{{ item }}"
  with_file:
    - public_keys/mercury-farm3

