# Copyright (c) 2017 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/consul-cluster/defaults/main.yml

consul_cluster_infoblox_delegate: 127.0.0.1
consul_cluster_infoblox_dns_view: internal

# FIXME this is broken and assumes all consul-servers are in a single cluster
consul_cluster_server_ips: "{{ groups['consul-servers'] | map('extract', hostvars, 'openstack_server') |  map(attribute='accessIPv4') | list }}"

#consul_cluster_leader_ip: "{{ (consul_cluster_info.results | map(attribute='consul_info') | map(attribute='consul') | map(attribute='leader_attr') | unique | list)[0].split(':')[0] }}"
#consul_cluster_leader_ip: "{{ (consul_cluster_info.results[0].consul_info.consul.leader_attr | split(':'))[0] }}"

consul_cluster_leader: "{% for server in consul_cluster_info.results %}{% if server.consul_info.consul.leader == 'true' %}{{ server.item }}{% endif %}{% endfor %}"

consul_cluster_leader_acl_master_token: "{{ hostvars[consul_cluster_leader].consul_server_acl_master_token }}"

