# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/mesos-slave/vars/main.yml

mesos_slave_bin: "{{ mesos_prefix }}/sbin/mesos-slave"
mesos_slave_zk_uri: "zk://{% for host in groups['zookeepers'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"
mesos_slave_hostname: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
mesos_slave_work_dir: "{{ hgi_dir }}/tmp"
mesos_slave_executor_registration_timeout: "5mins"

# The supervisor name for this supervised program
mesos_slave_supervisor_program: "mesos-slave"

# Path to a file containing a single line with
# the 'principal' and 'secret' separated by whitespace.
# Path could be of the form 'file:///path/to/file' or '/path/to/file'
mesos_slave_credential_file: "{{ hgi_conf_dir }}/mesos-slave.credential"

# mesos_slave_containerizers:
#  - "docker,mesos" (requires docker >= 1.0)
#  - "mesos"
mesos_slave_containerizers: "docker,mesos"

# mesos_slave_isolation: 
#  - "posix/cpu,posix/mem"
#  - "cgroups/cpu,cgroups/mem" (requires root)
#  - "external"
mesos_slave_isolation: "posix/cpu,posix/mem"
