# Vault contains:
#  s3_credentials:
#    sanger-ceph-mercury:
#      s3_host: xxx
#      s3_access_key: xxx
#      s3_secret_key: xxx
#    sanger-ceph-mercurykeep:
#      s3_host: xxx
#      s3_access_key: xxx
#      s3_secret_key: xxx

---
