# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/tasks/main.yml

- name: create local HGI conf directory
  file: state=directory path={{ hgi_conf_dir }} owner=mercury group=hgi mode=2770

- name: create local HGI log directory
  file: state=directory path={{ hgi_log_dir }} owner=mercury group=hgi mode=2770

- name: create local HGI pid directory
  file: state=directory path={{ hgi_pid_dir }} owner=mercury group=hgi mode=2770

- name: create local HGI run directory
  file: state=directory path={{ hgi_run_dir }} owner=mercury group=hgi mode=2770

- name: create local HGI certs directory
  file: state=directory path={{ hgi_certs_dir }} owner=mercury group=hgi mode=2770

- name: create supervisord conf directory
  file: state=directory path={{ supervisord_conf_dir }} owner=mercury group=hgi mode=2770

- name: supervisord startup script 
  template: src=mercury_supervisord.j2 dest={{ supervisord_ctl }} owner=mercury group=hgi mode=0750
  notify: restart supervisord
  tags: supervisord

- name: supervisord configuration file
  template: src=mercury_supervisord.conf.j2 dest={{ supervisord_conf }} owner=mercury group=hgi mode=0750
  notify: reload supervisord
  tags: supervisord

- name: cron entry to start supervisord on boot
  cron: name="start supervisord on boot" special_time=reboot job="bash -c \"{{ supervisord_ctl }} force-stop && {{ supervisord_ctl }} start\""
  tags: supervisord

- name: cron entry to start supervisord if not running (every 5 minutes)
  cron: name="start supervisord if not running" minute="*/5" job="{{ cronic_cmd }} bash -c \"{{ supervisord_ctl }} status || ({{ supervisord_ctl }} start && exit 1)\""
  tags: supervisord

- name: install *.hgi.internal.sanger.ac.uk TLS certificate
  copy: content="{{ pem_WILDCARD_hgi_internal_sanger_ac_uk_cert }}" dest="{{ hgi_certs_dir }}/WILDCARD_hgi_internal_sanger_ac_uk-cert.pem"
  tags: security

- name: install *.hgi.internal.sanger.ac.uk TLS key
  copy: content="{{ pem_WILDCARD_hgi_internal_sanger_ac_uk_key }}" dest="{{ hgi_certs_dir }}/WILDCARD_hgi_internal_sanger_ac_uk-key.pem" mode=0600
  tags: security

- name: generate hgi htpasswd file
  htpasswd: path="{{ hgi_conf_dir }}/htpasswd" name="{{ hgi_username }}" password="{{ hgi_password }}" state=present
  tags: security
