# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-systems.
#
# hgi-systems is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: site.yml

# set up non-host infrastructure
- include: gitlab-projects.yml

# make sure openstack instances are bootstrapped and facts are set
# TODO: migrate to dynamic inventory?
- include: openstack-instances-bootstrap.yml

# create dynamic groups for hosts based on OS
- hosts: all:!non-hosts
  tasks:
    - group_by: key=os_{{ ansible_distribution }}-{{ ansible_distribution_version }} # e.g. "os_Ubuntu_14.04"
    - group_by: key=os_{{ ansible_distribution }} # e.g. "os_Ubuntu"
    - group_by: key=os_family_{{ ansible_os_family }} # e.g. "os_Debian"

# when image-building, make sure we apply common role even if no other groups apply
- hosts: image-building
  roles: 
    - common

# playbooks that need nonroot host hgi infrastructure
- include: mesos-masters.yml
- include: zookeepers.yml
- include: marathoners.yml
- include: chronosians.yml
- include: mesos-slaves.yml
- include: bamboosians.yml

# playbooks that only support root hosts
- include: cookie-jars.yml
- include: cookie-monsters.yml
- include: dockerers.yml
- include: gitlab-runners.yml
- include: consul-servers.yml
- include: ssh-gateways.yml
- include: openstack-tenant-cleaners.yml
- include: arvados.yml
- include: arvados-crunchers.yml
- include: spark.yml

# higher-level infrastructure built on top of hosts
- include: consul-clusters.yml
