# Copyright (c) 2014 Genome Research Ltd.
#
# Author: Joshua C. Randall <jcrandall@alum.mit.edu>
#
# This file is part of hgi-ansible.
#
# hgi-ansible is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
---
# file: roles/common/vars/main.yml

supervisorctl_bin: "/software/hgi/pkglocal/supervisor-3.1.1/bin-wrap/supervisorctl"

supervisord_ctl: "{{ hgi_conf_dir }}/mercury_supervisord"
supervisord_bin: "/software/hgi/pkglocal/supervisor-3.1.1/bin/supervisord"
supervisord_pythonpath: "/software/hgi/pkglocal/supervisor-3.1.1/lib/python2.7/site-packages"
supervisord_conf: "{{ hgi_conf_dir }}/mercury_supervisord.conf"
supervisord_port: "9999"
supervisord_username: "{{ hgi_username }}"
supervisord_password: "{{ hgi_password }}"
supervisord_sock: "{{ hgi_conf_dir}}/mercury_supervisord.sock"
supervisord_pid_dir: "{{ hgi_pid_dir }}"
supervisord_log_dir: "{{ hgi_log_dir }}"
supervisord_conf_dir: "{{ hgi_conf_dir }}/mercury_supervisord.d"

cronic_bin: /software/hgi/pkglocal/cronic-3/bin/cronic
cronic_mailx_bin: /usr/bin/mailx
cronic_email_recipients: hgi@sanger.ac.uk
cronic_email_sender: '\"From: mercury@sanger.ac.uk\"'
cronic_email_subject: '\"Cronic report from $HOSTNAME\"'
cronic_cmd: "{{ cronic_bin }} -p '{{ cronic_mailx_bin }} -s {{ cronic_email_subject }} -a {{ cronic_email_sender }} {{ cronic_email_recipients }}'"
